#!/usr/bin/env bash
# config web2 to be like web 1
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo 'Ceci n'est pas une page' | sudo tee /var/www/html/404.html
sudo service nginx restart
