#!/usr/bin/env bash
# Bash script that pings an IP address
#+ the script passes an argument
#+ accepts string as an argument
#+ ping the IP 5 times
if [ "$#" -eq 0]; then
	echo "Usage: Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
