#!/usr/bin/env bash
#display time for 12 hours and 59 minutes
#display hours: 0 to 12
#display minutes: 0 to 59

hour=0
while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -lt 60 ]
    do
        echo "$minute"
        minute=$((minute+1))
    done
    hour=$((hour+1))
done
