#!/usr/bin/env bash
# Display "Best School" 10 times

scrpt="school"
if [ -e "$scrpt" ]
then
	echo "school file exists"
	if [ -s "$scrpt" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$scrpt" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
