#!/usr/bin/env bash
# config ubuntu server to an IP address
# to localhost and facebook hostname

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
